export default images = {
    homeBanner: require('../assets/icon.png'),
    arrow: require('../assets/images/arrowRight.png'),
    arrowLeft: require('../assets/images/arrowLeft3.png'),
    logo: require('../assets/images/logo.jpg'),
    profilePicture: require('../assets/images/profile.jpg'),
    search: require('../assets/images/search2.png'),
    menu: require('../assets/images/menu7.png'),
    productOne: require('../assets/images/products/clothe13.jpg'),
    productTwo: require('../assets/images/products/clothe12.jpg'),
    productThree: require('../assets/images/products/clothe15.jpg'),
    productFor: require('../assets/images/products/clothe17.jpg'),
    productFive: require('../assets/images/products/clothe19.jpg'),
    productSix: require('../assets/images/products/clothe18.jpg'),
    productSeven: require('../assets/images/products/clothe01.jpg'),
    productHeith: require('../assets/images/products/clothe11.jpg'),
    productNine: require('../assets/images/products/clothe04.jpg'),
    bag: require('../assets/images/bag.jpg'),
}